// src/components/BlogCard.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Calendar, ExternalLink, ArrowRight } from 'lucide-vue-next'

interface BlogPost {
  id: string
  title: string
  slug: string
  description: string | null
  coverImage: string | null
  source: string
  originalLink: string | null
  createdAt: string
}

const props = defineProps<{
  post: BlogPost
}>()

const isMedium = computed(() => props.post.source === 'MEDIUM')

const date = computed(() =>
  new Date(props.post.createdAt).toLocaleDateString('id-ID', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })
)
</script>

<template>
  <router-link
    :to="`/blog/${post.slug}`"
    :style="{
      display: 'block',
      borderRadius: '0.75rem',
      overflow: 'hidden',
      transition: 'all 0.3s',
      background: 'var(--bg-card)',
      border: '1px solid var(--border-primary)',
      textDecoration: 'none',
    }"
  >
    <!-- Thumbnail -->
    <div v-if="post.coverImage" style="position: relative; width: 100%; height: 12rem; overflow: hidden">
      <img
        :src="post.coverImage"
        :alt="post.title"
        style="width: 100%; height: 100%; object-fit: cover; transition: transform 0.3s"
      />
    </div>

    <!-- Content -->
    <div style="padding: 1.5rem">
      <h3
        class="line-clamp-2"
        :style="{
          fontSize: '1.25rem',
          fontWeight: 700,
          marginBottom: '0.75rem',
          color: 'var(--text-primary)',
          transition: 'color 0.2s',
        }"
      >
        {{ post.title }}
      </h3>

      <p
        v-if="post.description"
        class="line-clamp-3"
        :style="{
          fontSize: '0.875rem',
          marginBottom: '1rem',
          color: 'var(--text-secondary)',
        }"
      >
        {{ post.description }}
      </p>

      <!-- Meta Info -->
      <div style="display: flex; flex-wrap: wrap; align-items: center; gap: 1rem; font-size: 0.875rem">
        <div :style="{ display: 'flex', alignItems: 'center', gap: '0.375rem', color: 'var(--text-muted)' }">
          <Calendar :size="14" />
          <span>{{ date }}</span>
        </div>

        <div
          :style="{
            padding: '0.125rem 0.5rem',
            fontSize: '0.75rem',
            borderRadius: '9999px',
            display: 'flex',
            alignItems: 'center',
            gap: '0.25rem',
            background: isMedium ? '#000' : 'var(--accent-bg)',
            color: isMedium ? '#fff' : 'var(--accent-text)',
          }"
        >
          {{ isMedium ? 'Medium' : 'Local' }}
          <ExternalLink v-if="isMedium" :size="10" />
        </div>
      </div>

      <!-- Read More -->
      <div
        :style="{
          marginTop: '1rem',
          display: 'flex',
          alignItems: 'center',
          gap: '0.25rem',
          fontSize: '0.875rem',
          fontWeight: 500,
          color: 'var(--text-accent)',
        }"
      >
        <span>{{ isMedium ? 'Baca di Medium' : 'Baca selengkapnya' }}</span>
        <ArrowRight :size="16" />
      </div>
    </div>
  </router-link>
</template>

// app/components/BlogCard.tsx
import Link from 'next/link';
import { Calendar, Tag, ArrowRight, ExternalLink } from 'lucide-react';

interface BlogPost {
  id: string;
  title: string;
  slug: string;
  description: string | null;
  content: string | null;
  coverImage: string | null;
  source: string; // 'LOCAL' | 'MEDIUM'
  originalLink: string | null;
  createdAt: Date | string;
}

interface BlogCardProps {
  post: BlogPost;
  isDarkMode: boolean;
}

export default function BlogCard({ post, isDarkMode }: BlogCardProps) {
  const isMedium = post.source === 'MEDIUM';
  // Always link to internal detail page - even for Medium posts
  const href = `/blog/${post.slug}`;

  const date = new Date(post.createdAt).toLocaleDateString('id-ID', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  return (
    <Link
      href={href}
      className={`group block rounded-xl overflow-hidden transition-all duration-300 hover:scale-[1.02] ${
        isDarkMode
          ? 'bg-slate-700 hover:bg-slate-600 shadow-lg shadow-slate-900/50 border border-transparent'
          : 'bg-white hover:bg-gray-50 shadow hover:shadow-md border border-gray-300'
      }`}
    >
      {/* Thumbnail */}
      {post.coverImage && (
        <div className="relative w-full h-48 overflow-hidden">
          <img
            src={post.coverImage}
            alt={post.title}
            className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-110"
          />
        </div>
      )}

      {/* Content */}
      <div className="p-6">
        {/* Title */}
        <h3
          className={`text-xl font-bold mb-3 line-clamp-2 transition-colors ${
            isDarkMode
              ? 'text-white group-hover:text-cyan-300'
              : 'text-gray-900 group-hover:text-blue-600'
          }`}
        >
          {post.title}
        </h3>

        {/* Description */}
        <p
          className={`text-sm mb-4 line-clamp-3 ${
            isDarkMode ? 'text-gray-300' : 'text-gray-700'
          }`}
        >
          {post.description}
        </p>

        {/* Meta Info */}
        <div className="flex flex-wrap items-center gap-4 text-sm">
          {/* Date */}
          <div
            className={`flex items-center gap-1.5 ${
              isDarkMode ? 'text-gray-400' : 'text-gray-500'
            }`}
          >
            <Calendar size={14} />
            <span>{date}</span>
          </div>

          {/* Source Badge */}
          <div
             className={`px-2 py-0.5 text-xs rounded-full flex items-center gap-1 ${
               isMedium 
                ? 'bg-black text-white' 
                : isDarkMode ? 'bg-blue-900/40 text-blue-300' : 'bg-blue-100 text-blue-700'
             }`}
          >
             {isMedium ? 'Medium' : 'Local'}
             {isMedium && <ExternalLink size={10} />}
          </div>
        </div>

        {/* Read More Indicator */}
        <div
          className={`mt-4 flex items-center gap-1 text-sm font-medium transition-colors ${
            isDarkMode
              ? 'text-cyan-400 group-hover:text-cyan-300'
              : 'text-blue-600 group-hover:text-blue-500'
          }`}
        >
          <span>{isMedium ? 'Baca di Medium' : 'Baca selengkapnya'}</span>
          <ArrowRight
            size={16}
            className="transition-transform group-hover:translate-x-1"
          />
        </div>
      </div>
    </Link>
  );
}
