// src/components/CommentSection.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useAuthStore } from '@/stores/auth'
import { MessageSquare, Send } from 'lucide-vue-next'

const props = defineProps<{
  slug: string
}>()

const auth = useAuthStore()

interface Comment {
  id: string
  content: string
  createdAt: string
  author: {
    name: string | null
    image: string | null
  }
}

const comments = ref<Comment[]>([])
const newComment = ref('')
const loading = ref(false)
const fetching = ref(true)

async function fetchComments() {
  try {
    const res = await fetch(`/api/blog/${props.slug}/comments`)
    if (res.ok) {
      comments.value = await res.json()
    }
  } catch (error) {
    console.error('Failed to fetch comments', error)
  } finally {
    fetching.value = false
  }
}

async function handleSubmit() {
  if (!newComment.value.trim()) return
  loading.value = true
  try {
    const res = await fetch(`/api/blog/${props.slug}/comments`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ content: newComment.value }),
    })
    if (res.ok) {
      newComment.value = ''
      fetchComments()
    } else {
      alert('Failed to post comment')
    }
  } catch (error) {
    console.error(error)
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  fetchComments()
})
</script>

<template>
  <div :style="{ marginTop: '3rem', paddingTop: '2rem', borderTop: '1px solid var(--border-primary)' }">
    <h3
      :style="{
        fontSize: '1.25rem',
        fontWeight: 700,
        marginBottom: '1.5rem',
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
        color: 'var(--text-primary)',
      }"
    >
      <MessageSquare :size="20" />
      Comments ({{ comments.length }})
    </h3>

    <!-- Comment Form -->
    <div style="margin-bottom: 2rem">
      <template v-if="auth.isAuthenticated">
        <div style="display: flex; flex-direction: column; gap: 1rem">
          <div style="display: flex; align-items: center; justify-content: space-between">
            <div style="display: flex; align-items: center; gap: 0.75rem">
              <img
                v-if="auth.user?.image"
                :src="auth.user.image"
                alt="User"
                style="width: 2rem; height: 2rem; border-radius: 9999px"
              />
              <span :style="{ fontSize: '0.875rem', color: 'var(--text-secondary)' }">
                Logged in as <strong>{{ auth.user?.name }}</strong>
              </span>
            </div>
            <button
              @click="auth.signOut()"
              style="
                font-size: 0.875rem;
                color: #ef4444;
                border: none;
                background: none;
                cursor: pointer;
                text-decoration: underline;
              "
            >
              Sign out
            </button>
          </div>

          <form @submit.prevent="handleSubmit" style="position: relative">
            <textarea
              v-model="newComment"
              placeholder="What are your thoughts?"
              :disabled="loading"
              :style="{
                width: '100%',
                padding: '1rem',
                borderRadius: '0.75rem',
                border: '1px solid var(--border-input)',
                background: 'var(--bg-card)',
                color: 'var(--text-primary)',
                outline: 'none',
                resize: 'none',
                height: '8rem',
                fontFamily: 'inherit',
                fontSize: '0.875rem',
              }"
            />
            <button
              type="submit"
              :disabled="loading || !newComment.trim()"
              :style="{
                position: 'absolute',
                bottom: '1rem',
                right: '1rem',
                padding: '0.5rem',
                background: '#2563eb',
                color: '#fff',
                borderRadius: '0.5rem',
                border: 'none',
                cursor: 'pointer',
                opacity: loading || !newComment.trim() ? 0.5 : 1,
              }"
            >
              <Send :size="18" />
            </button>
          </form>
        </div>
      </template>

      <template v-else>
        <div
          :style="{
            padding: '1.5rem',
            background: 'var(--bg-card)',
            borderRadius: '0.75rem',
            textAlign: 'center',
          }"
        >
          <p :style="{ color: 'var(--text-muted)', marginBottom: '1rem' }">
            Sign in to leave a comment
          </p>
          <button
            @click="auth.signIn('google')"
            :style="{
              display: 'inline-flex',
              alignItems: 'center',
              gap: '0.5rem',
              padding: '0.5rem 1.5rem',
              background: '#fff',
              border: '1px solid #d1d5db',
              color: '#374151',
              borderRadius: '0.5rem',
              cursor: 'pointer',
              fontFamily: 'inherit',
              fontSize: '0.875rem',
            }"
          >
            Sign in with Google
          </button>
        </div>
      </template>
    </div>

    <!-- Comments List -->
    <div style="display: flex; flex-direction: column; gap: 1.5rem">
      <p v-if="fetching" style="text-align: center; color: var(--text-muted)">Loading comments...</p>

      <template v-else-if="comments.length > 0">
        <div v-for="comment in comments" :key="comment.id" class="animate-fade-in-up" style="display: flex; gap: 1rem">
          <div style="flex-shrink: 0">
            <img
              v-if="comment.author.image"
              :src="comment.author.image"
              :alt="comment.author.name || 'User'"
              style="width: 2.5rem; height: 2.5rem; border-radius: 9999px"
            />
            <div
              v-else
              :style="{
                width: '2.5rem',
                height: '2.5rem',
                borderRadius: '9999px',
                background: 'var(--badge-bg)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '1.125rem',
                fontWeight: 700,
                color: 'var(--text-muted)',
              }"
            >
              {{ (comment.author.name || '?')[0].toUpperCase() }}
            </div>
          </div>
          <div style="flex: 1">
            <div
              :style="{
                background: 'var(--bg-card)',
                padding: '1rem',
                borderRadius: '0.75rem',
                borderTopLeftRadius: 0,
              }"
            >
              <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 0.5rem">
                <span :style="{ fontWeight: 600, color: 'var(--text-primary)' }">
                  {{ comment.author.name || 'Anonymous' }}
                </span>
                <span :style="{ fontSize: '0.75rem', color: 'var(--text-muted)' }">
                  {{ new Date(comment.createdAt).toLocaleDateString() }}
                </span>
              </div>
              <p :style="{ color: 'var(--text-secondary)', overflowWrap: 'break-word' }">
                {{ comment.content }}
              </p>
            </div>
          </div>
        </div>
      </template>

      <p v-else :style="{ textAlign: 'center', color: 'var(--text-muted)', fontStyle: 'italic' }">
        No comments yet. Be the first to share your thoughts!
      </p>
    </div>
  </div>
</template>

// app/components/CommentSection.tsx
'use client';

import { useState, useEffect } from 'react';
import { useSession, signIn, signOut } from 'next-auth/react';
import { MessageSquare, Send } from 'lucide-react';

interface Comment {
  id: string;
  content: string;
  createdAt: string;
  author: {
    name: string | null;
    image: string | null;
  };
}

export default function CommentSection({ slug }: { slug: string }) {
  const { data: session } = useSession();
  const [comments, setComments] = useState<Comment[]>([]);
  const [newComment, setNewComment] = useState('');
  const [loading, setLoading] = useState(false);
  const [fetching, setFetching] = useState(true);

  useEffect(() => {
    fetchComments();
  }, [slug]);

  const fetchComments = async () => {
    try {
      const res = await fetch(`/api/blog/${slug}/comments`);
      if (res.ok) {
        const data = await res.json();
        setComments(data);
      }
    } catch (error) {
      console.error('Failed to fetch comments', error);
    } finally {
      setFetching(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newComment.trim()) return;

    setLoading(true);
    try {
      const res = await fetch(`/api/blog/${slug}/comments`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ content: newComment }),
      });

      if (res.ok) {
        setNewComment('');
        fetchComments(); // Refresh list
      } else {
        alert('Failed to post comment');
      }
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="mt-12 pt-8 border-t border-gray-200 dark:border-slate-700">
      <h3 className="text-xl font-bold mb-6 flex items-center gap-2 text-gray-900 dark:text-white">
        <MessageSquare size={20} />
        Comments ({comments.length})
      </h3>

      {/* Comment Form */}
      <div className="mb-8">
        {session ? (
          <div className="space-y-4">
            {/* User info and logout */}
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                {session.user?.image && (
                  <img src={session.user.image} alt="User" className="w-8 h-8 rounded-full" />
                )}
                <span className="text-sm text-gray-700 dark:text-gray-300">
                  Logged in as <strong>{session.user?.name}</strong>
                </span>
              </div>
              <button
                onClick={() => signOut()}
                className="text-sm text-red-500 hover:text-red-600 hover:underline transition-colors"
              >
                Sign out
              </button>
            </div>
            {/* Comment form */}
            <form onSubmit={handleSubmit} className="relative">
              <textarea
                value={newComment}
                onChange={(e) => setNewComment(e.target.value)}
                placeholder="What are your thoughts?"
                className="w-full p-4 rounded-xl border border-gray-200 dark:border-slate-700 bg-gray-50 dark:bg-slate-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 outline-none transition-all resize-none h-32"
                disabled={loading}
              />
              <button
                type="submit"
                disabled={loading || !newComment.trim()}
                className="absolute bottom-4 right-4 p-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Send size={18} />
              </button>
            </form>
          </div>
        ) : (
          <div className="p-6 bg-gray-50 dark:bg-slate-800 rounded-xl text-center">
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Sign in to leave a comment
            </p>
            <button
              onClick={() => signIn('google')}
              className="inline-flex items-center gap-2 px-6 py-2 bg-white border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors shadow-sm"
            >
              <svg className="w-5 h-5" viewBox="0 0 24 24">
                <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/>
                <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/>
                <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/>
                <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/>
              </svg>
              Sign in with Google
            </button>
          </div>
        )}
      </div>

      {/* Comments List */}
      <div className="space-y-6">
        {fetching ? (
            <p className="text-center text-gray-500">Loading comments...</p>
        ) : comments.length > 0 ? (
          comments.map((comment) => (
            <div key={comment.id} className="flex gap-4 animate-fade-in-up">
              <div className="flex-shrink-0">
                {comment.author.image ? (
                   <img
                    src={comment.author.image}
                    alt={comment.author.name || 'User'}
                    className="w-10 h-10 rounded-full"
                  />
                ) : (
                  <div className="w-10 h-10 rounded-full bg-gray-200 dark:bg-slate-700 flex items-center justify-center">
                    <span className="text-lg font-bold text-gray-500 dark:text-gray-400">
                      {(comment.author.name || '?')[0].toUpperCase()}
                    </span>
                  </div>
                )}
              </div>
              <div className="flex-1">
                <div className="bg-gray-50 dark:bg-slate-800 p-4 rounded-xl rounded-tl-none">
                  <div className="flex items-center justify-between mb-2">
                    <span className="font-semibold text-gray-900 dark:text-white">
                      {comment.author.name || 'Anonymous'}
                    </span>
                    <span className="text-xs text-gray-500 dark:text-gray-400">
                      {new Date(comment.createdAt).toLocaleDateString()}
                    </span>
                  </div>
                  <p className="text-gray-700 dark:text-gray-300 break-words">
                    {comment.content}
                  </p>
                </div>
              </div>
            </div>
          ))
        ) : (
          <p className="text-center text-gray-500 dark:text-gray-400 italic">
            No comments yet. Be the first to share your thoughts!
          </p>
        )}
      </div>
    </div>
  );
}
