// src/components/NowPlayingBubble.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { Music } from 'lucide-vue-next'
import { useThemeStore } from '@/stores/theme'

const props = defineProps<{
  username: string
  apiKey: string
}>()

const theme = useThemeStore()

interface Track {
  name: string
  artist: string
  album?: string
  image?: string
  url?: string
  nowplaying?: boolean
}

const track = ref<Track | null>(null)
const isExpanded = ref(false)
let interval: ReturnType<typeof setInterval> | null = null

async function fetchNowPlaying() {
  if (!props.username || !props.apiKey) return
  try {
    const url = `https://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=${props.username}&api_key=${props.apiKey}&format=json&limit=1`
    const res = await fetch(url)
    const data = await res.json()
    const recent = data.recenttracks?.track?.[0]
    if (recent && recent['@attr']?.nowplaying) {
      track.value = {
        name: recent.name,
        artist: recent.artist['#text'],
        album: recent.album['#text'],
        image: recent.image?.[2]?.['#text'] || '',
        url: recent.url,
        nowplaying: true,
      }
    } else {
      track.value = null
    }
  } catch {
    track.value = null
  }
}

onMounted(() => {
  fetchNowPlaying()
  interval = setInterval(fetchNowPlaying, 30_000)
})

onUnmounted(() => {
  if (interval) clearInterval(interval)
})
</script>

<template>
  <template v-if="track">
    <!-- Collapsed -->
    <button
      v-if="!isExpanded"
      @click="isExpanded = true"
      class="animate-fade-in-up"
      :style="{
        position: 'fixed',
        bottom: '1.5rem',
        right: '1.5rem',
        zIndex: 50,
        width: '3rem',
        height: '3rem',
        borderRadius: '9999px',
        boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
        border: '1px solid var(--border-primary)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
        transition: 'transform 0.2s',
        background: theme.isDarkMode ? 'rgba(255,255,255,0.95)' : 'rgba(30,41,59,0.95)',
        color: theme.isDarkMode ? '#1e293b' : '#ffffff',
      }"
    >
      <Music :size="20" />
    </button>

    <!-- Expanded -->
    <div
      v-else
      class="animate-fade-in-up"
      :style="{
        position: 'fixed',
        bottom: '1.5rem',
        right: '1.5rem',
        zIndex: 50,
        boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
        borderRadius: '9999px',
        display: 'flex',
        alignItems: 'center',
        padding: '0.5rem 1rem',
        gap: '0.5rem',
        border: '1px solid var(--border-primary)',
        minWidth: '200px',
        background: theme.isDarkMode ? 'rgba(255,255,255,0.95)' : 'rgba(30,41,59,0.95)',
      }"
    >
      <button @click="isExpanded = false" style="flex-shrink: 0; border: none; background: none; cursor: pointer; padding: 0">
        <img
          v-if="track.image"
          :src="track.image"
          :alt="track.name"
          style="width: 2rem; height: 2rem; border-radius: 9999px; object-fit: cover"
        />
        <div
          v-else
          style="
            width: 2rem;
            height: 2rem;
            border-radius: 9999px;
            background: var(--badge-bg);
            display: flex;
            align-items: center;
            justify-content: center;
          "
        >
          <Music :size="16" />
        </div>
      </button>
      <div style="display: flex; flex-direction: column; flex: 1; min-width: 0">
        <span
          :style="{
            fontSize: '0.75rem',
            color: theme.isDarkMode ? '#6b7280' : '#9ca3af',
          }"
        >
          Naufal is listening...
        </span>
        <a
          :href="track.url"
          target="_blank"
          rel="noopener noreferrer"
          class="truncate"
          :style="{
            fontSize: '0.875rem',
            fontWeight: 600,
            color: theme.isDarkMode ? '#0891b2' : '#22d3ee',
            textDecoration: 'none',
          }"
          :title="track.name"
        >
          {{ track.name }}
        </a>
        <span
          class="truncate"
          :style="{
            fontSize: '0.75rem',
            color: theme.isDarkMode ? '#374151' : '#d1d5db',
          }"
          :title="track.artist"
        >
          {{ track.artist }}
        </span>
      </div>
    </div>
  </template>
</template>

// app/components/NowPlayingBubble.tsx
'use client';

import { useEffect, useState } from 'react';
import { Music } from 'lucide-react';

interface NowPlayingBubbleProps {
 username: string;
 apiKey: string;
 isDarkMode?: boolean;
}

interface Track {
 name: string;
 artist: string;
 album?: string;
 image?: string;
 url?: string;
 nowplaying?: boolean;
}

export default function NowPlayingBubble({
 username,
 apiKey,
 isDarkMode = false,
}: NowPlayingBubbleProps) {
 const [track, setTrack] = useState<Track | null>(null);
 const [isExpanded, setIsExpanded] = useState(false);

 useEffect(() => {
  const fetchNowPlaying = async () => {
   const url = `https://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=${username}&api_key=${apiKey}&format=json&limit=1`;
   const res = await fetch(url);
   const data = await res.json();
   const recent = data.recenttracks?.track?.[0];
   if (recent && recent['@attr']?.nowplaying) {
    setTrack({
     name: recent.name,
     artist: recent.artist['#text'],
     album: recent.album['#text'],
     image: recent.image?.[2]?.['#text'] || '',
     url: recent.url,
     nowplaying: true,
    });
   } else {
    setTrack(null);
   }
  };
  fetchNowPlaying();
  const interval = setInterval(fetchNowPlaying, 30_000); // update every 30s
  return () => clearInterval(interval);
 }, [username, apiKey]);

 if (!track) return null;

 // Collapsed state - just a small music icon
 if (!isExpanded) {
  return (
   <button
    onClick={() => setIsExpanded(true)}
    className={`fixed bottom-6 right-6 z-50 w-12 h-12 rounded-full shadow-lg border flex items-center justify-center animate-fade-in-up hover:scale-110 transition-all duration-200 ${
     isDarkMode
      ? 'bg-white/95 border-gray-200 hover:bg-white'
      : 'bg-slate-800/95 border-slate-700 hover:bg-slate-800'
    }`}
   >
    <Music size={20} className={isDarkMode ? 'text-slate-800' : 'text-white'} />
   </button>
  );
 }

 // Expanded state - full info
 return (
  <div
   className={`fixed bottom-6 right-6 z-50 shadow-lg rounded-full flex items-center px-4 py-2 gap-2 border animate-fade-in-up ${
    isDarkMode
     ? 'bg-white/95 border-gray-200'
     : 'bg-slate-800/95 border-slate-700'
   }`}
   style={{ minWidth: 200 }}
  >
   <button onClick={() => setIsExpanded(false)} className="flex-shrink-0">
    {track.image ? (
     <img
      src={track.image}
      alt={track.name}
      className="w-8 h-8 rounded-full object-cover"
     />
    ) : (
     <div className="w-8 h-8 rounded-full bg-gray-300 dark:bg-gray-600 flex items-center justify-center">
      <Music size={16} className="text-gray-600 dark:text-gray-300" />
     </div>
    )}
   </button>
   <div className="flex flex-col flex-1 min-w-0">
    <span
     className={`text-xs ${isDarkMode ? 'text-gray-500' : 'text-gray-400'}`}
    >
     Naufal is listening...
    </span>
    <a
     href={track.url}
     target="_blank"
     rel="noopener noreferrer"
     className={`text-sm font-semibold hover:underline truncate ${
      isDarkMode ? 'text-cyan-600' : 'text-cyan-400'
     }`}
     title={track.name}
    >
     {track.name}
    </a>
    <span
     className={`text-xs truncate ${
      isDarkMode ? 'text-gray-700' : 'text-gray-300'
     }`}
     title={track.artist}
    >
     {track.artist}
    </span>
   </div>
  </div>
 );
}
